# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: publish image

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:

  publish:
    name: publish image
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/publish-container.yaml@62fed61ee4a732fb309006ef6c55f348b7db3441    # v0.2.0
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: twdps/gha-container-builder
      op-version: 2.28.0
      cosign-version: 2.2.4
      syft-version: 1.4.1
      oras-version: 1.1.0
      sign-image: true
      sbom: true
      gren: true
      release-message: New release ThoughtWorks-DPS/gha-container-builder
      before-publish: true
