# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: publish image

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:

  publish:
    name: publish image
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/publish-container.yaml@4baf5677df945981d15017f0ffed8acaba1c6d8f     # v0.2.1
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: twdps/gha-container-builder
      release-tag: latest
      sign-image: true
      sbom: true
      gren: true
      release-message: New release ThoughtWorks-DPS/gha-container-builder
      before-publish: true
